from http import HTTPStatus
from typing import Any, Optional, Union

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.get_product_list_request import GetProductListRequest
from ...models.http_validation_error import HTTPValidationError
from ...models.response_model import ResponseModel
from ...types import Response


def _get_kwargs(
    *,
    body: GetProductListRequest,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v1/tiktok/creator/get_product_analytics_list",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: Union[AuthenticatedClient, Client], response: httpx.Response
) -> Optional[Union[HTTPValidationError, ResponseModel]]:
    if response.status_code == 200:
        response_200 = ResponseModel.from_dict(response.json())

        return response_200
    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())

        return response_422
    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: Union[AuthenticatedClient, Client], response: httpx.Response
) -> Response[Union[HTTPValidationError, ResponseModel]]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: GetProductListRequest,
) -> Response[Union[HTTPValidationError, ResponseModel]]:
    r"""获取创作者商品列表分析/Get Creator Product List Analytics

     # [中文]
    ### 用途:
    - 获取 TikTok Shop 创作者账号在指定时间范围内推广的商品列表及其销售数据分析。
    - 支持按商品成交额、商品上架时间排序，可分页查询。

    ### 返回内容说明:
    - `segments`（分段数据列表）:
      - `filter.creator_id`: 创作者账号 ID
      - `list_control`:
        - `rules`: 列表排序规则（如按成交额、商品 ID 排序）
        - `next_pagination`: 翻页信息（是否还有更多页、下一页页码、总页数、总记录数）
      - `timed_lists`: 每个时间段内的商品数据，包括：
        - `product`:
          - `id`: 商品 ID
          - `name`: 商品标题
          - `cover_image.thumb_url_list`: 商品封面图列表
        - `item_sold_cnt`: 销售商品数量
        - `revenue.amount`: 该商品带来的总成交金额（GMV）
        - `commission.amount`: 该商品预估佣金收入

    ### 备注:
    - 此接口仅适用于 TikTok Shop 创作者账号。
    - 数据以自然月或自定义时间范围统计。
    - 默认排序为成交额（GMV）从高到低。

    ### 参数:
    - cookie: 用户 Cookie 字符串（用于身份认证）
    - start_date: 开始日期，格式为 'YYYY-MM-DD'，如 '2025-04-01'
    - end_date: 结束日期，格式为 'YYYY-MM-DD'，如 '2025-05-01'
    - page: 页码，默认为第一页 `0`
    - proxy: 可选 HTTP 代理地址，如不使用可省略
        - 示例格式: `http://username:password@host:port`

    ### 返回:
    - 创作者账号商品列表及商品销售分析数据

    # [English]
    ### Purpose:
    - Retrieve the list of products promoted by a TikTok Shop creator account within a specified time
    range, along with their sales analytics.
    - Supports sorting by revenue or product publish time and allows pagination.

    ### Response Fields:
    - `segments` (List of segmented data):
      - `filter.creator_id`: Creator account ID
      - `list_control`:
        - `rules`: Sorting rules (e.g., by revenue, by product ID)
        - `next_pagination`: Pagination info (has more pages, next page number, total pages, total
    records)
      - `timed_lists`: List of product statistics within each time range, including:
        - `product`:
          - `id`: Product ID
          - `name`: Product title
          - `cover_image.thumb_url_list`: List of product thumbnail URLs
        - `item_sold_cnt`: Number of items sold
        - `revenue.amount`: Total Gross Merchandise Value (GMV) generated by the product
        - `commission.amount`: Estimated commission income from the product

    ### Notes:
    - This API is only available for TikTok Shop creator accounts.
    - Data is aggregated by natural month or the customized date range.
    - Default sorting is by GMV in descending order.

    ### Parameters:
    - cookie: User Cookie string for authentication
    - start_date: Start date, formatted as 'YYYY-MM-DD', e.g., '2025-04-01'
    - end_date: End date, formatted as 'YYYY-MM-DD', e.g., '2025-05-01'
    - page: Page number, default is the first page `0`
    - proxy: Optional HTTP proxy address, can be omitted if not used
        - Example format: `http://username:password@host:port`

    ### Return:
    - Creator product list and corresponding sales analytics data

    # [示例/Example]
    ```json
    {
      \"cookie\": \"your_cookie\",
      \"start_date\": \"2025-04-01\",
      \"end_date\": \"2025-05-01\",
      \"page\": 0
    }
    ```

    Args:
        body (GetProductListRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[HTTPValidationError, ResponseModel]]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: GetProductListRequest,
) -> Optional[Union[HTTPValidationError, ResponseModel]]:
    r"""获取创作者商品列表分析/Get Creator Product List Analytics

     # [中文]
    ### 用途:
    - 获取 TikTok Shop 创作者账号在指定时间范围内推广的商品列表及其销售数据分析。
    - 支持按商品成交额、商品上架时间排序，可分页查询。

    ### 返回内容说明:
    - `segments`（分段数据列表）:
      - `filter.creator_id`: 创作者账号 ID
      - `list_control`:
        - `rules`: 列表排序规则（如按成交额、商品 ID 排序）
        - `next_pagination`: 翻页信息（是否还有更多页、下一页页码、总页数、总记录数）
      - `timed_lists`: 每个时间段内的商品数据，包括：
        - `product`:
          - `id`: 商品 ID
          - `name`: 商品标题
          - `cover_image.thumb_url_list`: 商品封面图列表
        - `item_sold_cnt`: 销售商品数量
        - `revenue.amount`: 该商品带来的总成交金额（GMV）
        - `commission.amount`: 该商品预估佣金收入

    ### 备注:
    - 此接口仅适用于 TikTok Shop 创作者账号。
    - 数据以自然月或自定义时间范围统计。
    - 默认排序为成交额（GMV）从高到低。

    ### 参数:
    - cookie: 用户 Cookie 字符串（用于身份认证）
    - start_date: 开始日期，格式为 'YYYY-MM-DD'，如 '2025-04-01'
    - end_date: 结束日期，格式为 'YYYY-MM-DD'，如 '2025-05-01'
    - page: 页码，默认为第一页 `0`
    - proxy: 可选 HTTP 代理地址，如不使用可省略
        - 示例格式: `http://username:password@host:port`

    ### 返回:
    - 创作者账号商品列表及商品销售分析数据

    # [English]
    ### Purpose:
    - Retrieve the list of products promoted by a TikTok Shop creator account within a specified time
    range, along with their sales analytics.
    - Supports sorting by revenue or product publish time and allows pagination.

    ### Response Fields:
    - `segments` (List of segmented data):
      - `filter.creator_id`: Creator account ID
      - `list_control`:
        - `rules`: Sorting rules (e.g., by revenue, by product ID)
        - `next_pagination`: Pagination info (has more pages, next page number, total pages, total
    records)
      - `timed_lists`: List of product statistics within each time range, including:
        - `product`:
          - `id`: Product ID
          - `name`: Product title
          - `cover_image.thumb_url_list`: List of product thumbnail URLs
        - `item_sold_cnt`: Number of items sold
        - `revenue.amount`: Total Gross Merchandise Value (GMV) generated by the product
        - `commission.amount`: Estimated commission income from the product

    ### Notes:
    - This API is only available for TikTok Shop creator accounts.
    - Data is aggregated by natural month or the customized date range.
    - Default sorting is by GMV in descending order.

    ### Parameters:
    - cookie: User Cookie string for authentication
    - start_date: Start date, formatted as 'YYYY-MM-DD', e.g., '2025-04-01'
    - end_date: End date, formatted as 'YYYY-MM-DD', e.g., '2025-05-01'
    - page: Page number, default is the first page `0`
    - proxy: Optional HTTP proxy address, can be omitted if not used
        - Example format: `http://username:password@host:port`

    ### Return:
    - Creator product list and corresponding sales analytics data

    # [示例/Example]
    ```json
    {
      \"cookie\": \"your_cookie\",
      \"start_date\": \"2025-04-01\",
      \"end_date\": \"2025-05-01\",
      \"page\": 0
    }
    ```

    Args:
        body (GetProductListRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[HTTPValidationError, ResponseModel]
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: GetProductListRequest,
) -> Response[Union[HTTPValidationError, ResponseModel]]:
    r"""获取创作者商品列表分析/Get Creator Product List Analytics

     # [中文]
    ### 用途:
    - 获取 TikTok Shop 创作者账号在指定时间范围内推广的商品列表及其销售数据分析。
    - 支持按商品成交额、商品上架时间排序，可分页查询。

    ### 返回内容说明:
    - `segments`（分段数据列表）:
      - `filter.creator_id`: 创作者账号 ID
      - `list_control`:
        - `rules`: 列表排序规则（如按成交额、商品 ID 排序）
        - `next_pagination`: 翻页信息（是否还有更多页、下一页页码、总页数、总记录数）
      - `timed_lists`: 每个时间段内的商品数据，包括：
        - `product`:
          - `id`: 商品 ID
          - `name`: 商品标题
          - `cover_image.thumb_url_list`: 商品封面图列表
        - `item_sold_cnt`: 销售商品数量
        - `revenue.amount`: 该商品带来的总成交金额（GMV）
        - `commission.amount`: 该商品预估佣金收入

    ### 备注:
    - 此接口仅适用于 TikTok Shop 创作者账号。
    - 数据以自然月或自定义时间范围统计。
    - 默认排序为成交额（GMV）从高到低。

    ### 参数:
    - cookie: 用户 Cookie 字符串（用于身份认证）
    - start_date: 开始日期，格式为 'YYYY-MM-DD'，如 '2025-04-01'
    - end_date: 结束日期，格式为 'YYYY-MM-DD'，如 '2025-05-01'
    - page: 页码，默认为第一页 `0`
    - proxy: 可选 HTTP 代理地址，如不使用可省略
        - 示例格式: `http://username:password@host:port`

    ### 返回:
    - 创作者账号商品列表及商品销售分析数据

    # [English]
    ### Purpose:
    - Retrieve the list of products promoted by a TikTok Shop creator account within a specified time
    range, along with their sales analytics.
    - Supports sorting by revenue or product publish time and allows pagination.

    ### Response Fields:
    - `segments` (List of segmented data):
      - `filter.creator_id`: Creator account ID
      - `list_control`:
        - `rules`: Sorting rules (e.g., by revenue, by product ID)
        - `next_pagination`: Pagination info (has more pages, next page number, total pages, total
    records)
      - `timed_lists`: List of product statistics within each time range, including:
        - `product`:
          - `id`: Product ID
          - `name`: Product title
          - `cover_image.thumb_url_list`: List of product thumbnail URLs
        - `item_sold_cnt`: Number of items sold
        - `revenue.amount`: Total Gross Merchandise Value (GMV) generated by the product
        - `commission.amount`: Estimated commission income from the product

    ### Notes:
    - This API is only available for TikTok Shop creator accounts.
    - Data is aggregated by natural month or the customized date range.
    - Default sorting is by GMV in descending order.

    ### Parameters:
    - cookie: User Cookie string for authentication
    - start_date: Start date, formatted as 'YYYY-MM-DD', e.g., '2025-04-01'
    - end_date: End date, formatted as 'YYYY-MM-DD', e.g., '2025-05-01'
    - page: Page number, default is the first page `0`
    - proxy: Optional HTTP proxy address, can be omitted if not used
        - Example format: `http://username:password@host:port`

    ### Return:
    - Creator product list and corresponding sales analytics data

    # [示例/Example]
    ```json
    {
      \"cookie\": \"your_cookie\",
      \"start_date\": \"2025-04-01\",
      \"end_date\": \"2025-05-01\",
      \"page\": 0
    }
    ```

    Args:
        body (GetProductListRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[HTTPValidationError, ResponseModel]]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: GetProductListRequest,
) -> Optional[Union[HTTPValidationError, ResponseModel]]:
    r"""获取创作者商品列表分析/Get Creator Product List Analytics

     # [中文]
    ### 用途:
    - 获取 TikTok Shop 创作者账号在指定时间范围内推广的商品列表及其销售数据分析。
    - 支持按商品成交额、商品上架时间排序，可分页查询。

    ### 返回内容说明:
    - `segments`（分段数据列表）:
      - `filter.creator_id`: 创作者账号 ID
      - `list_control`:
        - `rules`: 列表排序规则（如按成交额、商品 ID 排序）
        - `next_pagination`: 翻页信息（是否还有更多页、下一页页码、总页数、总记录数）
      - `timed_lists`: 每个时间段内的商品数据，包括：
        - `product`:
          - `id`: 商品 ID
          - `name`: 商品标题
          - `cover_image.thumb_url_list`: 商品封面图列表
        - `item_sold_cnt`: 销售商品数量
        - `revenue.amount`: 该商品带来的总成交金额（GMV）
        - `commission.amount`: 该商品预估佣金收入

    ### 备注:
    - 此接口仅适用于 TikTok Shop 创作者账号。
    - 数据以自然月或自定义时间范围统计。
    - 默认排序为成交额（GMV）从高到低。

    ### 参数:
    - cookie: 用户 Cookie 字符串（用于身份认证）
    - start_date: 开始日期，格式为 'YYYY-MM-DD'，如 '2025-04-01'
    - end_date: 结束日期，格式为 'YYYY-MM-DD'，如 '2025-05-01'
    - page: 页码，默认为第一页 `0`
    - proxy: 可选 HTTP 代理地址，如不使用可省略
        - 示例格式: `http://username:password@host:port`

    ### 返回:
    - 创作者账号商品列表及商品销售分析数据

    # [English]
    ### Purpose:
    - Retrieve the list of products promoted by a TikTok Shop creator account within a specified time
    range, along with their sales analytics.
    - Supports sorting by revenue or product publish time and allows pagination.

    ### Response Fields:
    - `segments` (List of segmented data):
      - `filter.creator_id`: Creator account ID
      - `list_control`:
        - `rules`: Sorting rules (e.g., by revenue, by product ID)
        - `next_pagination`: Pagination info (has more pages, next page number, total pages, total
    records)
      - `timed_lists`: List of product statistics within each time range, including:
        - `product`:
          - `id`: Product ID
          - `name`: Product title
          - `cover_image.thumb_url_list`: List of product thumbnail URLs
        - `item_sold_cnt`: Number of items sold
        - `revenue.amount`: Total Gross Merchandise Value (GMV) generated by the product
        - `commission.amount`: Estimated commission income from the product

    ### Notes:
    - This API is only available for TikTok Shop creator accounts.
    - Data is aggregated by natural month or the customized date range.
    - Default sorting is by GMV in descending order.

    ### Parameters:
    - cookie: User Cookie string for authentication
    - start_date: Start date, formatted as 'YYYY-MM-DD', e.g., '2025-04-01'
    - end_date: End date, formatted as 'YYYY-MM-DD', e.g., '2025-05-01'
    - page: Page number, default is the first page `0`
    - proxy: Optional HTTP proxy address, can be omitted if not used
        - Example format: `http://username:password@host:port`

    ### Return:
    - Creator product list and corresponding sales analytics data

    # [示例/Example]
    ```json
    {
      \"cookie\": \"your_cookie\",
      \"start_date\": \"2025-04-01\",
      \"end_date\": \"2025-05-01\",
      \"page\": 0
    }
    ```

    Args:
        body (GetProductListRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[HTTPValidationError, ResponseModel]
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
        )
    ).parsed
