from http import HTTPStatus
from typing import Any, Optional, Union

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.get_video_overview_request import GetVideoOverviewRequest
from ...models.http_validation_error import HTTPValidationError
from ...models.response_model import ResponseModel
from ...types import Response


def _get_kwargs(
    *,
    body: GetVideoOverviewRequest,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v1/tiktok/creator/get_video_analytics_summary",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: Union[AuthenticatedClient, Client], response: httpx.Response
) -> Optional[Union[HTTPValidationError, ResponseModel]]:
    if response.status_code == 200:
        response_200 = ResponseModel.from_dict(response.json())

        return response_200
    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())

        return response_422
    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: Union[AuthenticatedClient, Client], response: httpx.Response
) -> Response[Union[HTTPValidationError, ResponseModel]]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: GetVideoOverviewRequest,
) -> Response[Union[HTTPValidationError, ResponseModel]]:
    r"""获取创作者视频概览/Get Creator Video Overview

     # [中文]
    ### 用途:
    - 获取 TikTok Shop 创作者账号在指定时间范围内的视频表现概览。
    - 默认统计从调用当天向前 30 天的数据（或按平台设定的自然月分段）。
    - 适合用于视频表现分析，例如视频数量、播放量、粉丝增长、成交数据等。

    ### 返回内容说明:
    - `segments`（分段数据列表）:
      - `time_selector`: 时间范围设置信息（周期、起止时间戳、时区、语言）
      - `filter.creator_id`: 创作者账号 ID
      - `timed_stats`: 每个时间段的视频表现数据，包含：
        - `vv_cnt`: 视频播放量（Video Views Count）
        - `new_follower_cnt`: 新增粉丝数量
        - `video_cnt`: 发布视频数量
        - `gmv.amount`: 视频带货产生的 GMV 金额
        - `items_sold`: 售出商品数量

    ### 备注:
    - 此接口仅适用于 TikTok Shop 创作者账号。
    - 如果某个时间段无数据，返回的 `stats` 字段可能为空 `{}`。

    ### 参数:
    - cookie: 用户 Cookie 字符串（用于身份认证）
    - proxy: 可选 HTTP 代理地址，如不使用可省略
        - 示例格式: `http://username:password@host:port`

    ### 返回:
    - 创作者账号视频表现概览

    # [English]
    ### Purpose:
    - Retrieve a video performance overview for a TikTok Shop creator account over a specified time
    range.
    - By default, the API fetches data for the past 30 days (or full calendar month based on the
    platform settings).
    - Useful for analyzing metrics like video count, views, new followers, and generated GMV.

    ### Response Fields:
    - `segments` (List of segmented data):
      - `time_selector`: Time period settings (period, start/end timestamps, timezone, locale)
      - `filter.creator_id`: Creator account ID
      - `timed_stats`: Video performance statistics for each time segment, including:
        - `vv_cnt`: Video Views Count
        - `new_follower_cnt`: Number of new followers
        - `video_cnt`: Number of videos published
        - `gmv.amount`: Gross Merchandise Value generated by videos
        - `items_sold`: Number of items sold

    ### Notes:
    - This API is only available for TikTok Shop creator accounts.
    - If no data is available for a time segment, the `stats` field might be an empty `{}`.

    ### Parameters:
    - cookie: User Cookie string for authentication
    - proxy: Optional HTTP proxy address, can be omitted if not used
        - Example format: `http://username:password@host:port`

    ### Return:
    - Creator account video performance overview

    # [示例/Example]
    ```json
    {
      \"cookie\": \"your_cookie\"
    }
    ```

    Args:
        body (GetVideoOverviewRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[HTTPValidationError, ResponseModel]]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: GetVideoOverviewRequest,
) -> Optional[Union[HTTPValidationError, ResponseModel]]:
    r"""获取创作者视频概览/Get Creator Video Overview

     # [中文]
    ### 用途:
    - 获取 TikTok Shop 创作者账号在指定时间范围内的视频表现概览。
    - 默认统计从调用当天向前 30 天的数据（或按平台设定的自然月分段）。
    - 适合用于视频表现分析，例如视频数量、播放量、粉丝增长、成交数据等。

    ### 返回内容说明:
    - `segments`（分段数据列表）:
      - `time_selector`: 时间范围设置信息（周期、起止时间戳、时区、语言）
      - `filter.creator_id`: 创作者账号 ID
      - `timed_stats`: 每个时间段的视频表现数据，包含：
        - `vv_cnt`: 视频播放量（Video Views Count）
        - `new_follower_cnt`: 新增粉丝数量
        - `video_cnt`: 发布视频数量
        - `gmv.amount`: 视频带货产生的 GMV 金额
        - `items_sold`: 售出商品数量

    ### 备注:
    - 此接口仅适用于 TikTok Shop 创作者账号。
    - 如果某个时间段无数据，返回的 `stats` 字段可能为空 `{}`。

    ### 参数:
    - cookie: 用户 Cookie 字符串（用于身份认证）
    - proxy: 可选 HTTP 代理地址，如不使用可省略
        - 示例格式: `http://username:password@host:port`

    ### 返回:
    - 创作者账号视频表现概览

    # [English]
    ### Purpose:
    - Retrieve a video performance overview for a TikTok Shop creator account over a specified time
    range.
    - By default, the API fetches data for the past 30 days (or full calendar month based on the
    platform settings).
    - Useful for analyzing metrics like video count, views, new followers, and generated GMV.

    ### Response Fields:
    - `segments` (List of segmented data):
      - `time_selector`: Time period settings (period, start/end timestamps, timezone, locale)
      - `filter.creator_id`: Creator account ID
      - `timed_stats`: Video performance statistics for each time segment, including:
        - `vv_cnt`: Video Views Count
        - `new_follower_cnt`: Number of new followers
        - `video_cnt`: Number of videos published
        - `gmv.amount`: Gross Merchandise Value generated by videos
        - `items_sold`: Number of items sold

    ### Notes:
    - This API is only available for TikTok Shop creator accounts.
    - If no data is available for a time segment, the `stats` field might be an empty `{}`.

    ### Parameters:
    - cookie: User Cookie string for authentication
    - proxy: Optional HTTP proxy address, can be omitted if not used
        - Example format: `http://username:password@host:port`

    ### Return:
    - Creator account video performance overview

    # [示例/Example]
    ```json
    {
      \"cookie\": \"your_cookie\"
    }
    ```

    Args:
        body (GetVideoOverviewRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[HTTPValidationError, ResponseModel]
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: GetVideoOverviewRequest,
) -> Response[Union[HTTPValidationError, ResponseModel]]:
    r"""获取创作者视频概览/Get Creator Video Overview

     # [中文]
    ### 用途:
    - 获取 TikTok Shop 创作者账号在指定时间范围内的视频表现概览。
    - 默认统计从调用当天向前 30 天的数据（或按平台设定的自然月分段）。
    - 适合用于视频表现分析，例如视频数量、播放量、粉丝增长、成交数据等。

    ### 返回内容说明:
    - `segments`（分段数据列表）:
      - `time_selector`: 时间范围设置信息（周期、起止时间戳、时区、语言）
      - `filter.creator_id`: 创作者账号 ID
      - `timed_stats`: 每个时间段的视频表现数据，包含：
        - `vv_cnt`: 视频播放量（Video Views Count）
        - `new_follower_cnt`: 新增粉丝数量
        - `video_cnt`: 发布视频数量
        - `gmv.amount`: 视频带货产生的 GMV 金额
        - `items_sold`: 售出商品数量

    ### 备注:
    - 此接口仅适用于 TikTok Shop 创作者账号。
    - 如果某个时间段无数据，返回的 `stats` 字段可能为空 `{}`。

    ### 参数:
    - cookie: 用户 Cookie 字符串（用于身份认证）
    - proxy: 可选 HTTP 代理地址，如不使用可省略
        - 示例格式: `http://username:password@host:port`

    ### 返回:
    - 创作者账号视频表现概览

    # [English]
    ### Purpose:
    - Retrieve a video performance overview for a TikTok Shop creator account over a specified time
    range.
    - By default, the API fetches data for the past 30 days (or full calendar month based on the
    platform settings).
    - Useful for analyzing metrics like video count, views, new followers, and generated GMV.

    ### Response Fields:
    - `segments` (List of segmented data):
      - `time_selector`: Time period settings (period, start/end timestamps, timezone, locale)
      - `filter.creator_id`: Creator account ID
      - `timed_stats`: Video performance statistics for each time segment, including:
        - `vv_cnt`: Video Views Count
        - `new_follower_cnt`: Number of new followers
        - `video_cnt`: Number of videos published
        - `gmv.amount`: Gross Merchandise Value generated by videos
        - `items_sold`: Number of items sold

    ### Notes:
    - This API is only available for TikTok Shop creator accounts.
    - If no data is available for a time segment, the `stats` field might be an empty `{}`.

    ### Parameters:
    - cookie: User Cookie string for authentication
    - proxy: Optional HTTP proxy address, can be omitted if not used
        - Example format: `http://username:password@host:port`

    ### Return:
    - Creator account video performance overview

    # [示例/Example]
    ```json
    {
      \"cookie\": \"your_cookie\"
    }
    ```

    Args:
        body (GetVideoOverviewRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Union[HTTPValidationError, ResponseModel]]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: GetVideoOverviewRequest,
) -> Optional[Union[HTTPValidationError, ResponseModel]]:
    r"""获取创作者视频概览/Get Creator Video Overview

     # [中文]
    ### 用途:
    - 获取 TikTok Shop 创作者账号在指定时间范围内的视频表现概览。
    - 默认统计从调用当天向前 30 天的数据（或按平台设定的自然月分段）。
    - 适合用于视频表现分析，例如视频数量、播放量、粉丝增长、成交数据等。

    ### 返回内容说明:
    - `segments`（分段数据列表）:
      - `time_selector`: 时间范围设置信息（周期、起止时间戳、时区、语言）
      - `filter.creator_id`: 创作者账号 ID
      - `timed_stats`: 每个时间段的视频表现数据，包含：
        - `vv_cnt`: 视频播放量（Video Views Count）
        - `new_follower_cnt`: 新增粉丝数量
        - `video_cnt`: 发布视频数量
        - `gmv.amount`: 视频带货产生的 GMV 金额
        - `items_sold`: 售出商品数量

    ### 备注:
    - 此接口仅适用于 TikTok Shop 创作者账号。
    - 如果某个时间段无数据，返回的 `stats` 字段可能为空 `{}`。

    ### 参数:
    - cookie: 用户 Cookie 字符串（用于身份认证）
    - proxy: 可选 HTTP 代理地址，如不使用可省略
        - 示例格式: `http://username:password@host:port`

    ### 返回:
    - 创作者账号视频表现概览

    # [English]
    ### Purpose:
    - Retrieve a video performance overview for a TikTok Shop creator account over a specified time
    range.
    - By default, the API fetches data for the past 30 days (or full calendar month based on the
    platform settings).
    - Useful for analyzing metrics like video count, views, new followers, and generated GMV.

    ### Response Fields:
    - `segments` (List of segmented data):
      - `time_selector`: Time period settings (period, start/end timestamps, timezone, locale)
      - `filter.creator_id`: Creator account ID
      - `timed_stats`: Video performance statistics for each time segment, including:
        - `vv_cnt`: Video Views Count
        - `new_follower_cnt`: Number of new followers
        - `video_cnt`: Number of videos published
        - `gmv.amount`: Gross Merchandise Value generated by videos
        - `items_sold`: Number of items sold

    ### Notes:
    - This API is only available for TikTok Shop creator accounts.
    - If no data is available for a time segment, the `stats` field might be an empty `{}`.

    ### Parameters:
    - cookie: User Cookie string for authentication
    - proxy: Optional HTTP proxy address, can be omitted if not used
        - Example format: `http://username:password@host:port`

    ### Return:
    - Creator account video performance overview

    # [示例/Example]
    ```json
    {
      \"cookie\": \"your_cookie\"
    }
    ```

    Args:
        body (GetVideoOverviewRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Union[HTTPValidationError, ResponseModel]
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
        )
    ).parsed
